// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCGRoxMGRSamYvNzYc1SxFsqdBveTbTR8',
    appId: '1:705362808150:web:bcb78271d780ae98c89af7',
    messagingSenderId: '705362808150',
    projectId: 'intsaflutter',
    authDomain: 'intsaflutter.firebaseapp.com',
    storageBucket: 'intsaflutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK1f-0QyFoiNFKezNwpy7uHpblGpP3zX0',
    appId: '1:705362808150:android:76c5fb1023734c37c89af7',
    messagingSenderId: '705362808150',
    projectId: 'intsaflutter',
    storageBucket: 'intsaflutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXq7-8oiG3VeXzYE18kaQKBHRaguUpi-0',
    appId: '1:705362808150:ios:6c11d688577f8ed2c89af7',
    messagingSenderId: '705362808150',
    projectId: 'intsaflutter',
    storageBucket: 'intsaflutter.firebasestorage.app',
    iosBundleId: 'com.example.instagram1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXq7-8oiG3VeXzYE18kaQKBHRaguUpi-0',
    appId: '1:705362808150:ios:6c11d688577f8ed2c89af7',
    messagingSenderId: '705362808150',
    projectId: 'intsaflutter',
    storageBucket: 'intsaflutter.firebasestorage.app',
    iosBundleId: 'com.example.instagram1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCGRoxMGRSamYvNzYc1SxFsqdBveTbTR8',
    appId: '1:705362808150:web:807d201ae9aa9126c89af7',
    messagingSenderId: '705362808150',
    projectId: 'intsaflutter',
    authDomain: 'intsaflutter.firebaseapp.com',
    storageBucket: 'intsaflutter.firebasestorage.app',
  );
}
